apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-receiver
  namespace: argocd
spec:
  project: default
  
  source:
    helm:
      valueFiles:
        - env/prod/values_receiver_prod.yaml
    path: components/receiver/
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: main
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true