apiVersion: v1
kind: Service
metadata:
  name: prod-my-app-svc
spec:
  selector:
    app: prod-my-app
  type: NodePort
  ports:
  - port: 9000
    nodePort: 33000
    protocol: TCP
    targetPort: 5678
