apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-receiver
  namespace: argocd
spec:
  project: default
  
  source:
    helm:
      valueFiles:
        - env/stage/values_receiver_stage.yaml
    path: root-app/components/receiver/
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: main
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: stage

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true