apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.namespace }}-{{ .Values.name }}-service"
spec:
  selector:
    app: {{ .Values.app }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
