apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  namespace: argocd
spec:
  project: default

  source:
    helm:
      valueFiles:
        - env/qa/values_qa.yaml
    path: helm/sample-app
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
  
  destination: 
    server: {{ .Values.server }}
    namespace: {{ .Values.namespace }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
