name: app1
source:
  helm:
    valueFiles:
      - env/stage/values_stage.yaml
    path: helm/sample-app
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: HEAD

destination:
  server: https://kubernetes.default.svc
  namespace: qalatest

syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
