apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.namespace }}-{{ .Values.app }}-deployment"
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: hashicorp/http-echo
        args:
        - "-text=version 1-0-0"
        ports:
        - containerPort: 5678