apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.namespace }}-{{ .Values.app }}-service"
spec:
  selector:
    app: {{ .Values.app }}
  type: NodePort
  ports:
  - port: 9000
    nodePort: 31000
    protocol: TCP
    targetPort: 5678