apiVersion: v1
kind: Service
metadata:
  name: stage-my-app-svc
spec:
  selector:
    app: stage-my-app
  type: NodePort
  ports:
  - port: 9000
    nodePort: 31000
    protocol: TCP
    targetPort: 5678
