apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-argocd-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: HEAD
    path: without_kustomization/prod
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod-my-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
