apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-argocd-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: main
    path: root-app/pipelines/dev
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true