apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-argocd-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: main
    path: root-app/pipelines/prod
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true