apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.namespace }}-{{ .Values.name }}-service"
spec:
  selector:
    app: {{ .Values.app }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
