apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-argocd-app
  namespace: argocd
spec:
  project: default
  
  source:
    helm:
      valueFiles:
        - helm/sample-app/env/prod/values_prod.yaml
    path: helm/sample-app
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: HEAD
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod-receiver

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
