apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  
  source:
    helm:
      valueFiles:
        - values/values_app1.yaml
        - values/values_app2.yaml
    path: helm/root-app
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: HEAD
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
