apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-argocd-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: HEAD
    path: kustomization/env/stage
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: stage-my-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
