apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perf
  namespace: argocd
  labels:
    cluster: perf
spec:
  project: default
  
  source:
    helm:
      valueFiles:
        - values.yaml
    path: qa/pipelines/perf
    repoURL: git@github.com:jayagopalreddy/argocd.git
    targetRevision: HEAD
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: perf

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
